pull_request_rules:
  - name: Make sure PR are up to date before merging with rebase
    description: >-
      This automatically rebases PRs when they are out-of-date with the base
      branch to avoid semantic conflicts (next step is using a merge queue).
    conditions:
      - '#commits-behind >= 1'
    actions:
      rebase: 
  - name: rebase pull request when it's more than 10 commits behind main
    conditions:
      - '#commits-behind >= 1'
    actions:
      github_actions:
        workflow:
          dispatch:
            - workflow: rebase.yml
